INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Azucar', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Sal', NULL);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Almidón Maiz',null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Levadura química', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Goma Xantana', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Canela en polvo', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Harina de Arroz', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Harina de Garbanzo', NULL);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Harina de Maiz',null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Harina de Mijo', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Harina de Avena', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Masa Madre ECO', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Proteína de Gisante', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Hi Fibre 115', NULL);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Aroma de Vainilla',null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Margarina Hojaldre Vegano', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Margarina Crema Vegana', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Aceite de Coco RBD Eco', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Baking Box Surprise', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Baking Box Brownie', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Baking Box Bizcocho', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Molde redondo grande', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Molde cupcake', null);
INSERT INTO ingredient (id_ingredient, name, alergies) VALUES(null,'Molde cuadrado mediano', null);



INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Azucar',  '2020-12-20', 1, 1);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Sal', '2020-12-20', 10, 2);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Almidón Maiz','2020-12-20', 21, 3);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Levadura química', '2020-12-20', 10, 4);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Goma Xantana', '2020-12-20', 13, 5);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Canela en polvo', '2020-12-20', 5, 6);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Harina de Arroz', '2020-12-20', 20, 7);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Harina de Garbanzo', '2020-12-20', 25, 8);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Harina de Maiz','2020-12-20', 5, 9);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Harina de Mijo', '2020-12-20', 1, 10);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Harina de Avena', '2020-12-20', 1, 11);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Masa Madre ECO', '2020-12-20', 2, 12);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Proteína de Gisante', '2020-12-20', 4, 13);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Hi Fibre 115', '2020-12-20', 15, 14);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Aroma de Vainilla','2020-12-20', 5, 15);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Margarina Hojaldre Vegano', '2020-12-20', 28, 16);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Margarina Crema Vegana', '2020-12-20', 20, 17);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Aceite de Coco RBD Eco', '2020-12-20', 7, 18);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Baking Box Surprise', '2030-12-30', 20, 19);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Baking Box Brownie', '2030-12-30', 30, 20);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Baking Box Bizcocho', '2030-12-30', 20, 21);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Molde redondo grande', '2030-12-30', 40, 22);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Molde cupcake', '2030-12-30', 50, 23);
INSERT INTO stock_ingredients (id_stock, name, expiration_date, kg, id_ingredient) VALUES(null,'Molde cuadrado mediano', '2030-12-30', 30, 24);